data = [
    {"name": "Cristiano Ronaldo", "follower_count": 215, "description": "A Footballer", "country": "Portugal"},
    {"name": "Selena Gomez", "follower_count": 190, "description": "Singer and Actress", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 180, "description": "Media Personality and Businesswoman", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 160, "description": "Indian Cricketer", "country": "India"},
    {"name": "Taylor Swift", "follower_count": 200, "description": "Singer-Songwriter", "country": "USA"},
    {"name": "Lionel Messi", "follower_count": 210, "description": "Footballer", "country": "Argentina"},
    {"name": "Billie Eilish", "follower_count": 100, "description": "Singer-Songwriter", "country": "USA"},
    {"name": "Shah Rukh Khan", "follower_count": 90, "description": "Bollywood Actor", "country": "India"},
    {"name": "Dwayne Johnson", "follower_count": 170, "description": "Actor and Former Wrestler", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 185, "description": "Entrepreneur and Socialite", "country": "USA"},
    {"name": "Narendra Modi", "follower_count": 85, "description": "Prime Minister of India", "country": "India"},
    {"name": "Barack Obama", "follower_count": 130, "description": "Former US President", "country": "USA"},
    {"name": "Zendaya", "follower_count": 95, "description": "Actress and Singer", "country": "USA"},
    {"name": "Emma Watson", "follower_count": 80, "description": "Actress and Activist", "country": "UK"},
    {"name": "MS Dhoni", "follower_count": 70, "description": "Former Indian Cricketer", "country": "India"},
    {"name": "Drake", "follower_count": 120, "description": "Rapper and Singer", "country": "Canada"},
    {"name": "Ariana Grande", "follower_count": 175, "description": "Singer and Actress", "country": "USA"},
    {"name": "PewDiePie", "follower_count": 110, "description": "YouTuber and Content Creator", "country": "Sweden"},
    {"name": "Khabane Lame", "follower_count": 100, "description": "TikTok Star", "country": "Italy"},
    {"name": "Rihanna", "follower_count": 160, "description": "Singer and Businesswoman", "country": "Barbados"},
    {"name": "Kourtney Kardashian", "follower_count": 95, "description": "Media Personality", "country": "USA"},
    {"name": "David Beckham", "follower_count": 105, "description": "Former Footballer", "country": "UK"},
    {"name": "Chris Hemsworth", "follower_count": 115, "description": "Actor", "country": "Australia"},
    {"name": "Elon Musk", "follower_count": 140, "description": "CEO of Tesla and SpaceX", "country": "USA"},
]
